### ISSUE TITLE
Collect Vale output

### ISSUE THREAD

**Issue by parno** [project-everest/everest-ci#60] opened 2017-02-16 02:09 UTC
The Vale CI script doesn't seem to be collecting any output from Vale's build.  Looking at several of the most recent commits, e.g., 

http://everestdashboard.azurewebsites.net/buildDetails.cshtml?buildId=4772

Clicking on the links to stdout and stderr just give 404 responses.  If it's possible to extract timing information for the various files and display it, that would be quite useful too.

**Comment by msprotz** [comment] 2017-02-16 04:54
The links posted on slack are good, so it's got to be something in the dashboard that is not generating the URLs correctly.

**Comment by darrenge** [comment] 2017-02-16 21:05
I will take this issue and make sure it gets fixed on dashboard

**Comment by darrenge** [comment] 2017-02-17 00:30
This is fixed now.

The problem is that up to this point, the log files haven't really followed a standard naming convention.  Rob had to special case each one so the dashboard would know where to look.

For example - for Everest, it has "everest-test..." but vale had "vale-build..."

Going forward - any new build should have the log file follow the convention of "ProjectName-BuildType-commithash stuff".  If we do that, then there won't need to be any code changes in the dashboard. So for vale it would be "vale-x86 CI-"commit info...

**Closed by darrenge** 2017-02-17 00:30 UTC
Labels: bug, P1
